version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html  # Destination folder where Nginx serves files
hooks:
  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root

