apiVersion: v1
kind: Service
metadata:
  name: portfolio
spec:
  type: NodePort  # Use NodePort for local clusters
  ports:
    - port: 80         # External port
      targetPort: 80       # Container's internal port
      nodePort: 30008      # Optional: Node port (choose any available port in the range 30000-32767)
  selector:
    app: portfolio
