apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 4
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: pranjaltripathi01/portfolio-website  # Your image name
        ports:
        - containerPort: 80  # Change this if your app uses a different port
